import { NextResponse } from "next/server";
import { adminAuth, adminDb } from "../../../lib/firebase-admin";
import { canManageBranch } from "../../../lib/permissions";
import { DEFAULT_BRANCH_ID, getBranchScopeForUser, userCanAccessBranch } from "../../../lib/branches";
import { EXPENSE_CATEGORIES } from "../../../lib/expenses";

async function authenticateRequest(request) {
    const authHeader = request.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
        throw new Error("Missing or malformed Authorization header");
    }
    const token = authHeader.split("Bearer ")[1];
    const decodedToken = await adminAuth.verifyIdToken(token);
    const userDoc = await adminDb.collection("users").doc(decodedToken.uid).get();
    if (!userDoc.exists) {
        throw new Error("User profile not found");
    }
    const userData = userDoc.data();
    if (userData.status !== "approved") {
        throw new Error("User account is pending approval or disabled");
    }
    return userData;
}

// 1. READ: Own expenses, or (branch managers) every expense in their branch scope
export async function GET(request) {
    try {
        const user = await authenticateRequest(request);
        const { searchParams } = new URL(request.url);
        const statusFilter = searchParams.get("status");
        const branchScope = getBranchScopeForUser(user);
        const requestedBranchId = searchParams.get("branchId");
        const activeBranchId = requestedBranchId || branchScope.activeBranchId || DEFAULT_BRANCH_ID;

        let query = adminDb.collection("expenses");
        if (canManageBranch(user)) {
            query = query.where("branchId", "==", activeBranchId);
        } else {
            query = query.where("submittedByUid", "==", user.uid);
        }

        const snapshot = await query.get();
        const expenses = [];
        snapshot.forEach((doc) => {
            const expense = doc.data();
            if (!statusFilter || expense.status === statusFilter) {
                expenses.push(expense);
            }
        });
        expenses.sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime());
        return NextResponse.json(expenses, { status: 200 });
    } catch (error) {
        console.error("GET expenses error:", error);
        return NextResponse.json({ error: error.message || "Unauthorized" }, { status: 401 });
    }
}

// 2. CREATE: Staff submit a receipt for approval, OR (branch managers) add an
// expense directly — no receipt/approval queue required, since the admin
// adding it already IS the approver.
export async function POST(request) {
    try {
        const user = await authenticateRequest(request);
        const body = await request.json();
        const { amount, category, vendor, description, date, receiptUrl, receiptName, paymentMethod, isReimbursable, adminDirect } = body;

        const numericAmount = Number(amount);
        if (!numericAmount || numericAmount <= 0) {
            return NextResponse.json({ error: "A valid expense amount is required." }, { status: 400 });
        }

        const isDirectEntry = Boolean(adminDirect) && canManageBranch(user);
        if (!isDirectEntry && !receiptUrl) {
            return NextResponse.json({ error: "A receipt photo is required." }, { status: 400 });
        }

        const nowIso = new Date().toISOString();
        const id = `exp-${Date.now()}`;
        const reimbursable = Boolean(isReimbursable);
        const expense = {
            id,
            submittedByUid: user.uid,
            submittedByName: user.name || user.email || "Staff member",
            branchId: user.branchId || DEFAULT_BRANCH_ID,
            branchName: user.branchName || "Ottawa",
            amount: numericAmount,
            category: EXPENSE_CATEGORIES.includes(category) ? category : "Other",
            vendor: vendor || "",
            description: description || "",
            date: date || nowIso.split("T")[0],
            receiptUrl: receiptUrl || "",
            receiptName: receiptName || "",
            paymentMethod: paymentMethod || "Personal (Reimbursable)",
            isReimbursable: reimbursable,
            reimbursementStatus: reimbursable ? "pending" : "not_applicable",
            reimbursedVia: "",
            autoGenerated: false,
            status: isDirectEntry ? "approved" : "pending_approval",
            reviewedBy: isDirectEntry ? (user.email || user.uid) : "",
            reviewedAt: isDirectEntry ? nowIso : "",
            rejectionReason: "",
            syncStatus: "not_synced",
            createdAt: nowIso,
            updatedAt: nowIso
        };

        await adminDb.collection("expenses").doc(id).set(expense);
        return NextResponse.json({ message: isDirectEntry ? "Expense added." : "Expense submitted for approval.", expense }, { status: 200 });
    } catch (error) {
        console.error("POST expense error:", error);
        return NextResponse.json({ error: error.message || "Failed to submit expense." }, { status: 500 });
    }
}

// 3. UPDATE: Branch managers approve/reject/reimburse a submitted expense,
// or directly edit any expense's details.
export async function PUT(request) {
    try {
        const user = await authenticateRequest(request);
        const body = await request.json();
        const { action, expenseId, rejectionReason, reimbursedVia, patch } = body;

        if (!["approve", "reject", "mark_reimbursed", "edit"].includes(action)) {
            return NextResponse.json({ error: "Unsupported action." }, { status: 400 });
        }
        if (!canManageBranch(user)) {
            return NextResponse.json({ error: "Only branch admins can review expenses." }, { status: 403 });
        }
        if (!expenseId) {
            return NextResponse.json({ error: "Expense ID is required." }, { status: 400 });
        }

        const expenseRef = adminDb.collection("expenses").doc(expenseId);
        const expenseSnap = await expenseRef.get();
        if (!expenseSnap.exists) {
            return NextResponse.json({ error: "Expense not found." }, { status: 404 });
        }
        const expense = expenseSnap.data();
        if (!userCanAccessBranch(user, expense.branchId || DEFAULT_BRANCH_ID)) {
            return NextResponse.json({ error: "You cannot review this branch's expenses." }, { status: 403 });
        }

        const nowIso = new Date().toISOString();

        if (action === "edit") {
            const editable = ["amount", "category", "vendor", "description", "date", "paymentMethod", "isReimbursable"];
            const nextPatch = {};
            editable.forEach((key) => {
                if (patch && patch[key] !== undefined) nextPatch[key] = patch[key];
            });
            if (nextPatch.amount !== undefined) nextPatch.amount = Number(nextPatch.amount) || 0;
            if (nextPatch.category !== undefined && !EXPENSE_CATEGORIES.includes(nextPatch.category)) nextPatch.category = "Other";
            if (nextPatch.isReimbursable !== undefined) {
                nextPatch.isReimbursable = Boolean(nextPatch.isReimbursable);
                if (nextPatch.isReimbursable && expense.reimbursementStatus === "not_applicable") nextPatch.reimbursementStatus = "pending";
                if (!nextPatch.isReimbursable) nextPatch.reimbursementStatus = "not_applicable";
            }
            const edited = { ...expense, ...nextPatch, updatedAt: nowIso };
            await expenseRef.set(edited);
            return NextResponse.json({ message: "Expense updated.", expense: edited }, { status: 200 });
        }

        if (action === "mark_reimbursed") {
            if (!expense.isReimbursable) {
                return NextResponse.json({ error: "This expense was not flagged as reimbursable." }, { status: 400 });
            }
            if (!["bank", "cash"].includes(reimbursedVia)) {
                return NextResponse.json({ error: "Specify whether this was reimbursed from the bank or cash on hand." }, { status: 400 });
            }
            const reimbursed = {
                ...expense,
                reimbursementStatus: "paid",
                reimbursedVia,
                reimbursedBy: user.email || user.uid,
                reimbursedAt: nowIso,
                updatedAt: nowIso
            };
            await expenseRef.set(reimbursed);
            return NextResponse.json({ message: "Marked as reimbursed.", expense: reimbursed }, { status: 200 });
        }

        const updatedExpense = {
            ...expense,
            status: action === "approve" ? "approved" : "rejected",
            reviewedBy: user.email || user.uid,
            reviewedAt: nowIso,
            rejectionReason: action === "reject" ? (rejectionReason || "Rejected by branch admin.") : "",
            updatedAt: nowIso
        };

        await expenseRef.set(updatedExpense);
        return NextResponse.json({ message: `Expense ${action}d successfully.`, expense: updatedExpense }, { status: 200 });
    } catch (error) {
        console.error("PUT expense error:", error);
        return NextResponse.json({ error: error.message || "Failed to update expense." }, { status: 500 });
    }
}

// 4. DELETE: Branch managers can remove an expense record entirely.
export async function DELETE(request) {
    try {
        const user = await authenticateRequest(request);
        if (!canManageBranch(user)) {
            return NextResponse.json({ error: "Only branch admins can delete expenses." }, { status: 403 });
        }
        const { searchParams } = new URL(request.url);
        const expenseId = searchParams.get("id");
        if (!expenseId) {
            return NextResponse.json({ error: "Expense ID is required." }, { status: 400 });
        }
        const expenseRef = adminDb.collection("expenses").doc(expenseId);
        const expenseSnap = await expenseRef.get();
        if (!expenseSnap.exists) {
            return NextResponse.json({ error: "Expense not found." }, { status: 404 });
        }
        const expense = expenseSnap.data();
        if (!userCanAccessBranch(user, expense.branchId || DEFAULT_BRANCH_ID)) {
            return NextResponse.json({ error: "You cannot delete this branch's expenses." }, { status: 403 });
        }
        await expenseRef.delete();
        return NextResponse.json({ message: "Expense deleted." }, { status: 200 });
    } catch (error) {
        console.error("DELETE expense error:", error);
        return NextResponse.json({ error: error.message || "Failed to delete expense." }, { status: 500 });
    }
}
