import { FINANCE_SETTINGS_DEFAULTS } from "./financeDefaults";

const CARD_PAYMENT_METHODS = new Set(["credit-card", "card", "Card (Stripe)"]);

// Card payments cost a processing fee. Whenever a booking is paid (in full
// or partially) via card, this auto-creates/updates a linked expense record
// for that fee — so it shows up in the books without a human re-typing it.
// Idempotent: the expense id is derived from the booking id, so re-running
// this (e.g. the admin edits the amount) updates the same expense in place.
export async function maybeRecordCardProcessingFee(adminDb, booking) {
    const paymentMethod = booking.paymentMethod || "";
    const amountReceived = Number(booking.amountReceived ?? (booking.paymentStatus === "paid" ? booking.price : 0));
    const expenseId = `fee-${booking.id}`;
    const expenseRef = adminDb.collection("expenses").doc(expenseId);

    if (!CARD_PAYMENT_METHODS.has(paymentMethod) || amountReceived <= 0) {
        // Payment method changed away from card, or amount was reset —
        // remove any previously auto-generated fee for this booking.
        const existing = await expenseRef.get();
        if (existing.exists && existing.data().autoGenerated) {
            await expenseRef.delete();
        }
        return;
    }

    const settingsSnap = await adminDb.collection("settings").doc("finance").get();
    const settings = { ...FINANCE_SETTINGS_DEFAULTS, ...(settingsSnap.exists ? settingsSnap.data() : {}) };
    const feeAmount = Math.round((amountReceived * (settings.cardProcessingFeeRatePercent / 100) + Number(settings.cardProcessingFeeFixed || 0)) * 100) / 100;

    const nowIso = new Date().toISOString();
    await expenseRef.set({
        id: expenseId,
        submittedByUid: "system",
        submittedByName: "System (Card Processing)",
        branchId: booking.branchId || "ottawa-ca",
        branchName: booking.branchName || "Ottawa",
        amount: feeAmount,
        category: "Processing Fees",
        description: `Card processing fee — ${booking.clientName || "Booking"} (${booking.bookingNumber || booking.id})`,
        date: (booking.paidAt || nowIso).split("T")[0],
        receiptUrl: "",
        receiptName: "",
        status: "approved",
        reviewedBy: "system",
        reviewedAt: nowIso,
        rejectionReason: "",
        syncStatus: "not_synced",
        paymentMethod: "Company Bank",
        isReimbursable: false,
        reimbursementStatus: "not_applicable",
        autoGenerated: true,
        linkedBookingId: booking.id,
        createdAt: nowIso,
        updatedAt: nowIso,
    }, { merge: true });
}
